apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.app}}
  labels:
    app: {{ .Values.deployment.app}}
  annotations:
    # Add annotations here
    gial.lblw.dev/enabled: "true"
    gial.lblw.dev/subdomain-override: "{{ .Values.subdomain}}"
spec:
  selector:
    app: {{ .Values.deployment.app }}
  type: {{ .Values.service.type}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: http
      name: http
