apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: { { .Values.gateway.name } }
  namespace: { { .Values.gateway.namespace } }
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - { { .Values.gateway.host } }
      port:
        name: http
        number: 80
        protocol: HTTP
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: cluster-certs
      hosts:
        - { { .Values.gateway.host } }
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: { { .Values.virtualService.name } }
  namespace: { { .Values.gateway.namespace } }
spec:
  gateways:
    - { { .Values.gateway.name } }
  hosts:
    - { { .Values.gateway.host } }
  http:
    - name: bo-panel
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: { { .Values.virtualService.hostone } }
            port:
              number: 3000
